layout_spectrum: 0.3046595
color:
  saturation: 0.003493249
  brandStrength: 0.8347722
  lightness: 0.6326165
  rhythmicContrast: 0.3083187
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.1756272
name: Npower Solutions Ltd
